### ISSUE TITLE
issue with Libre2OOP US 14 day with xdrip+

### ISSUE THREAD

**Issue by Npavkov** [xdrip/xdrip_docs#57]
Xdrip+ keeps reporting during my sensor nfc scan to start sensor, that the sensor type is unknown returning libre1 and libre sensor of type 1 detected when I have a libre2 14 day sensor US.

**Comment by psonnera** [comment]
Libre 2 US is not supported by xDrip+ https://xdrip.readthedocs.io/en/latest/install/libre2/
