### ISSUE TITLE
Wear OS Watch Face

### ISSUE THREAD

**Issue by ghost** [xdrip/xdrip_docs#63]
The circular watch face on Wear OS isn't working for me. The green band around the outside that shows the time is there during its initial setup period when you choose the watch face, then disappears once it gets cgm data from xdrip. So, if I use it, there's no way to tell the time. 

Also, there's nothing in the documentation that explains what the different parts of that watch face are. I'm still not sure how the ring bar graph thing is supposed to work, when it shows up at all. 

I'm using a TicWatch E3 with Wear OS 3.5 and the latest version of xDrip+.

**Comment by psonnera** [comment]
Makes me feel really bad to see I wasn't able to answer a question and whom asked it deleted his GitHub account.
Wear OS 3.5 and now 5 represent serious challenges for customized watchfaces, not only for xDrip+.
